// Avatar storage format:
//   ''                              => render initials fallback
//   'dicebear:<style>:<seed>'       => SVG generated by DiceBear API
//   'data:image/...;base64,...'     => uploaded raster image

const DICEBEAR_BASE = 'https://api.dicebear.com/9.x';

export function avatarUrl(value, { size = 96 } = {}) {
  if (!value) return null;
  if (value.startsWith('data:')) return value;
  if (value.startsWith('dicebear:')) {
    const [, style, ...seedParts] = value.split(':');
    const seed = encodeURIComponent(seedParts.join(':') || 'default');
    return `${DICEBEAR_BASE}/${encodeURIComponent(style)}/svg?seed=${seed}&size=${size}`;
  }
  if (value.startsWith('http://') || value.startsWith('https://')) return value;
  return null;
}

// Available DiceBear styles for the custom avatar builder
export const AVATAR_STYLES = [
  { id: 'avataaars',   label: 'Cartoon faces' },
  { id: 'big-smile',   label: 'Big smile' },
  { id: 'lorelei',     label: 'Anime' },
  { id: 'notionists',  label: 'Sketch' },
  { id: 'micah',       label: 'Modern' },
  { id: 'adventurer',  label: 'Adventurer' },
  { id: 'pixel-art',   label: 'Pixel art' },
  { id: 'bottts',      label: 'Robots' },
  { id: 'fun-emoji',   label: 'Fun emoji' },
  { id: 'personas',    label: 'Personas' },
];

// 20 curated preset avatars, grouped into themed categories.
// We use DiceBear's procedural generator with hand-picked seeds
// rather than copyrighted character art (Tom & Jerry, One Piece, etc.).
export const PRESET_AVATARS = [
  // Cartoon
  { id: 'preset-cartoon-1', value: 'dicebear:avataaars:Sunny',     label: 'Sunny',     theme: 'Cartoon' },
  { id: 'preset-cartoon-2', value: 'dicebear:avataaars:Pickles',   label: 'Pickles',   theme: 'Cartoon' },
  { id: 'preset-cartoon-3', value: 'dicebear:avataaars:Mochi',     label: 'Mochi',     theme: 'Cartoon' },
  { id: 'preset-cartoon-4', value: 'dicebear:avataaars:Buddy',     label: 'Buddy',     theme: 'Cartoon' },
  { id: 'preset-cartoon-5', value: 'dicebear:big-smile:Cocoa',     label: 'Cocoa',     theme: 'Cartoon' },
  { id: 'preset-cartoon-6', value: 'dicebear:big-smile:Pumpkin',   label: 'Pumpkin',   theme: 'Cartoon' },

  // Anime-style
  { id: 'preset-anime-1', value: 'dicebear:lorelei:Sakura',        label: 'Sakura',    theme: 'Anime' },
  { id: 'preset-anime-2', value: 'dicebear:lorelei:Kenji',         label: 'Kenji',     theme: 'Anime' },
  { id: 'preset-anime-3', value: 'dicebear:lorelei:Hinata',        label: 'Hinata',    theme: 'Anime' },
  { id: 'preset-anime-4', value: 'dicebear:lorelei:Ren',           label: 'Ren',       theme: 'Anime' },
  { id: 'preset-anime-5', value: 'dicebear:notionists:Yuki',       label: 'Yuki',      theme: 'Anime' },
  { id: 'preset-anime-6', value: 'dicebear:notionists:Haru',       label: 'Haru',      theme: 'Anime' },

  // Adventure / personas
  { id: 'preset-adv-1', value: 'dicebear:adventurer:Rogue',        label: 'Rogue',     theme: 'Adventure' },
  { id: 'preset-adv-2', value: 'dicebear:adventurer:Sage',         label: 'Sage',      theme: 'Adventure' },
  { id: 'preset-adv-3', value: 'dicebear:micah:Indigo',            label: 'Indigo',    theme: 'Adventure' },
  { id: 'preset-adv-4', value: 'dicebear:personas:Atlas',          label: 'Atlas',     theme: 'Adventure' },

  // Pixel & Bots
  { id: 'preset-pixel-1', value: 'dicebear:pixel-art:Quartz',      label: 'Quartz',    theme: 'Pixel' },
  { id: 'preset-pixel-2', value: 'dicebear:pixel-art:Neon',        label: 'Neon',      theme: 'Pixel' },
  { id: 'preset-bot-1',   value: 'dicebear:bottts:Circuit',        label: 'Circuit',   theme: 'Robot' },
  { id: 'preset-bot-2',   value: 'dicebear:bottts:Pulse',          label: 'Pulse',     theme: 'Robot' },
];

export function randomSeed() {
  return Math.random().toString(36).slice(2, 10);
}

export function buildDicebearAvatar(style, seed) {
  return `dicebear:${style}:${seed}`;
}
